### ISSUE TITLE
Scaling in example_classification.py

### ISSUE THREAD

**Issue by mkowiel-ryvu** [scikit-fingerprints/scikit-fingerprints#138]
https://github.com/scikit-fingerprints/scikit-fingerprints/blob/master/benchmarking/example_classification.py#L108 
I think `fit_transform` should be changed to `transform`

```
        scaler = MinMaxScaler()
        X_fp_train = scaler.fit_transform(X_fp_train)
        X_fp_valid = scaler.transform(X_fp_valid)
        X_fp_test = scaler.transform(X_fp_test)
```

**Comment by j-adamczyk** [comment]
@mkowiel-ryvu you're right, this will be addressed in https://github.com/scikit-fingerprints/scikit-fingerprints/pull/129
