### ISSUE TITLE
Cannot Import Any Class from the Library in Google Colab

### ISSUE THREAD

**Issue by TENBrnak** [scikit-fingerprints/scikit-fingerprints#158]
When trying to import from the library on Google Colab, the code fails to run and responds with the following error:
ImportError: cannot import name 'Interval' from 'sklearn.utils' (/usr/local/lib/python3.10/dist-packages/sklearn/utils/init.py)

**Comment by j-adamczyk** [comment]
@TENBrnak this is with high probability a scikit-learn version issue. Which version are you using?

**Comment by TENBrnak** [comment]
I tried uninstalling scikit-learn and then having it installed by scikit-fingerprints, the version I uninstalled was 1.2.2 and the version this package installed was 1.4.2

**Comment by j-adamczyk** [comment]
@TENBrnak this is indeed an issue with scikit-learn internals changing (https://github.com/scikit-learn/scikit-learn/issues/28963). We'll fix this and make a release as soon as possible.

**Comment by TENBrnak** [comment]
No, 1.2.2 does not work, 1.4.2 does work.

**Comment by j-adamczyk** [comment]
@TENBrnak it should be working now, I checked additionally in Google Colab on both scikit-learn 1.2.2 and 1.4.2
