### ISSUE TITLE
Missing requires_conformers property

### ISSUE THREAD

**Issue by Hrovatin** [scikit-fingerprints/scikit-fingerprints#239]
Some of the FP classes miss `requires_conformers` property although they raise `ValueError: Passed data must be molecules (rdkit.Chem.rdChem.Mol instances) and each must have conf_id property set. You can use ConformerGenerator to add them.` if passing in smiles list.
Classes:
- USRFingerprint
- USRCATFingerprint

Package version:  1.7.0

**Comment by j-adamczyk** [comment]
You're right, this will be fixed in https://github.com/scikit-fingerprints/scikit-fingerprints/pull/242
