### ISSUE TITLE
Pharmacophore breaking for certain SMILES

### ISSUE THREAD

**Issue by cabreraalex** [scikit-fingerprints/scikit-fingerprints#258]
Hi! Thanks for this awesome library it's super helpful. 

I'm running into an issue where the Pharmacophore fingerprint is failing for this smiles:

https://www.chemspider.com/Chemical-Structure.16743716.html

**Comment by j-adamczyk** [comment]
@cabreraalex what exactly is failing? Do you get any stacktrace? If so, please provide it.

I started computing the fingerprint, and it doesn't fail, but takes a very long time. However, this is quite expected - pharmacophore fingerprint is by far the slowest one, and we had to exclude it from our ArXiv paper for this reason.

Simplifying a bit, it first matches a set of 8 SMARTS patterns for each atom (see [RDKit code](https://github.com/rdkit/rdkit/blob/4c37b03071181007316c306d874f75aa9f5cb7cf/rdkit/Chem/Pharm2D/Gobbi_Pharm2D.py) for definitions) to get its pharmacophoric types, and then does the exhaustive calculation of shortest distances, comparing all type combinations. This is why `"raw_bits"` variant results in as much as 39972 features.

If you know you need pharmacophoric atom types, I suggest using FCFP, which is ECFP with pharmacophoric atom invariants. This could also be introduced to Atom Pair, RDKit and Topological Torsion fingerprints with `invgen` (see `ecfp.py` for example). All those options will be much faster.

**Comment by cabreraalex** [comment]
Thanks so much for the thorough answer! The fingerprint would just time out for some batches of data, so definitely was just taking a ton of time and never completing in time. Definitely not necessary but maybe a warning in the docs would be helpful :). Will take a look at the other options!

**Comment by j-adamczyk** [comment]
We added a warning and a few expansions on this in https://github.com/scikit-fingerprints/scikit-fingerprints/pull/259 and https://github.com/scikit-fingerprints/scikit-fingerprints/pull/261. This will be in the next release. Furthermore, implementing https://github.com/scikit-fingerprints/scikit-fingerprints/issues/262 will make using pharmacophoric types much easier.

I will close this issue. Don't hesitate to open another if needed, or use the Discussions system.
