### ISSUE TITLE
Expose more TQDM kwargs (specifically 'leave')

### ISSUE THREAD

**Issue by LucaCappelletti94** [scikit-fingerprints/scikit-fingerprints#296]
Hi! Thank you for making this library.

At this time, the only parameter exposed regarding the [tqdm loading bar](https://github.com/scikit-fingerprints/scikit-fingerprints/blob/6293e86fe6390ec100ff454ff69685275332b414/skfp/utils/parallel.py#L10-L30) is verbose.

I'd like to expose the other kwargs, such as 'leave', which is the one that removes the loading bar from the output once it is done running.

I am not too sure regarding how to proceed, as adding all of the tqdm kwargs to all of the classes where 'verbose' appears seems like a poor choice. I think the best solution would be to create an Optional [dataclass](https://docs.python.org/3/library/dataclasses.html) argument, which by default is None, capturing all of the tqdm kwargs, and make this available everywhere the 'verbose' argument appears.

Do let me know whether you find this agreeable - if so I will proceed with the PR.

Luca

**Comment by j-adamczyk** [comment]
This is a good idea in general. Not exactly conforming to the scikit-learn API, but quite close. But I think that using kwargs dictionary would be simpler for maintenance than a custom class. In short, if non-empty `dict` is passed in `verbose` argument, we assume that a) verbose is true (existing conditions will work as-is) b) kwargs will be passed to `tqdm`.

**Comment by LucaCappelletti94** [comment]
I would lean towards using a custom type such as the one in my PR #298 since dictionaries would require validation. With a custom type, you get validation built-in.
