### ISSUE TITLE
Provide Descriptor Names When Available

### ISSUE THREAD

**Issue by Scienfitz** [scikit-fingerprints/scikit-fingerprints#307]
Hey, thanks for this great package :)
We are currently integrating it into our Bayesian experimental planner [baybe](https://github.com/emdgroup/baybe).

For descripor-based fingerprints  (such as mordred), we would in principle be interested in the descriptor names that should correspond to the feature names we get from the fingerprint. However, it seems this info is simply dropped by skfp. I.e. `get_feature_names_out` specifically just returns an enumeration, instead of the feature names like `ABC`, `MolWeight` etc

Would you be able to provide the actual feature names in such cases? This could be rather useful in downstream tasks such as model interpretation.

**Comment by j-adamczyk** [comment]
@Scienfitz great idea, we were considering it. This is definitely possible, but requires a bit of manual work for some fingerprints. In general:
1. Hashed fingerprints (e.g. ECFP) - leave as is, they don't have interpretable features
2. Substructure with SMARTS only (e.g. Klekota-Roth) - use SMARTS as feature names
3. Substructure with interpretable names (e.g. Laggner) - use those names
4. Descriptor-based (e.g. Mordred, autocorrelation, functional groups) - use appropriate feature names

We will probably get to do this in December or so. Of course, PRs are welcome to do this faster. Overriding `get_feature_names_out` in inheriting classes should be enough to make this work.

**Comment by Scienfitz** [comment]
Alright sounds good. Nothing to chagne from our end then, just waiting for the fixed names and they will automatically appear at some point.

Could try to provide the PRs for Mordred and rdkit2ddescriptors (not familiar with the others hence rather wouldn't touch those), but cannot promise

**Comment by j-adamczyk** [comment]
@Scienfitz we will track the progress in https://github.com/scikit-fingerprints/scikit-fingerprints/issues/310. I'm closing this issue now. Feel free to open another one if needed.
