### ISSUE TITLE
Expand automated transformation of inputs to `Mol` in fingerprint calculation

### ISSUE THREAD

**Issue by my-alaska** [scikit-fingerprints/scikit-fingerprints#339]
### Issue Description

The current implementation of the `_calculate_fingerprint()` method in fingerprint classes only supports the transformation of strings and molecule objects. During this process, the `ensure_mols()` function is called to validate the input data and transform it into a suitable format for further processing. This enables batch transformation of strings into molecule objects efficiently.

However, this functionality is currently limited to SMILES input strings. FASTA strings, commonly used for encoding amino acid sequences of peptides and proteins, need to be manually transformed into molecule objects before being passed to the `_calculate_fingerprint()` method.

This limitation creates a scenario where the entire dataset, transformed into molecule objects, must be stored in memory. For larger datasets, this can exceed the memory capacity of some machines.

### Proposed Solution

Enhancing the `ensure_mols()` function to include FASTA transformation functionality would address this limitation. By processing FASTA strings in batches passed to `_calculate_fingerprint()` method, memory usage could be optimized.

**Comment by j-adamczyk** [comment]
I don't think this is a necessary addition to the core library, but a good example of custom fingerprint and peptide-related functionality. I'll add this to the list of tutorials and close this issue.
