### ISSUE TITLE
Expand tests

### ISSUE THREAD

**Issue by j-adamczyk** [scikit-fingerprints/scikit-fingerprints#89]
For now, tests mostly check whether the parallel and sequential versions give the same result. This is important, but we also should verify other aspects, for example:
1. Shape
2. Value range
3. Returned data type
4. Invalid input validation (expected exceptions)

Additionally, we should have Scikit-learn API compliance tests:
1. Input/output format
2. Pipelines compatibility
3. Saving/loading transformers, including those in pipelines

**Comment by mjste** [comment]
additionally, tests which check if our implementation of some fingerprints are identical with original implementation

**Comment by j-adamczyk** [comment]
Partially done - Scikit-learn API compliance test done, and shape checks.

Still to do:
1. Value range
2. Data types
3. Invalid input validation (expected exceptions)
